# Generated by Django 5.0.7 on 2024-08-04 09:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
