# Generated by Django 5.0.7 on 2024-08-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_address_socialnetwork_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialnetwork',
            old_name='telegram',
            new_name='twitter',
        ),
    ]
