# Generated by Django 5.0.7 on 2024-08-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Subject',
            new_name='subject',
        ),
    ]
