# Generated by Django 5.0.7 on 2024-08-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_publication_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
    ]
